### ISSUE TITLE
Increase minimum CMake version to 3.5

### ISSUE THREAD

**Issue by phraemer** [TheLartians/Ccache.cmake#10]
CMake are going to drop compatibility with < CMake 3.5 and are already printing warnings in builds with 3.27

https://cmake.org/cmake/help/latest/release/3.27.html#deprecated-and-removed-features

Can we have a new release with the minimum version raised to at least 3.5 please?
Thanks.

**Comment by TheLartians** [comment]
Hey thanks for the issue! I wasn't aware of warnings being emitted with too low minimum version requirements. I think it would be reasonable to update the minimum version to 3.14.

**Comment by phraemer** [comment]
Thanks for the update. Build log is nice and clean again 😉
