### ISSUE TITLE
`launch-c` and `launch-cxx` must be in project directory.

### ISSUE THREAD

**Issue by jiverson002** [TheLartians/Ccache.cmake#3]
https://github.com/TheLartians/Ccache.cmake/blob/e0171fb971ff37618b882faa89965942c2305c5f/CMakeLists.txt#L22-L23

In the current version, the `launch-c` and `launch-cxx` files need to be present in the project directory (the project which is using Ccache.cmake). A use case that disallows this is to clone this project (Ccache.cmake) and then just include its main `CMakeLists.txt` file in place from the project using it. For example, when compiling a project I might say:

```sh
$ cmake -DCMAKE_PROJECT_a_project_INCLUDE=/path/to/Ccache.cmake ..
```

This statement works if I include `launch-c` and `launch-cxx` in the project directory, but not otherwise, due to the bare references to them in the main `CMakeLists.txt` file.

I suggest adding `${CMAKE_CURRENT_LIST_DIR}/` prefix to them to allow the project to be included from anywhere.

**Comment by TheLartians** [comment]
I've merged your PR and created a new release `v1.2.2` containing the changes!
