### ISSUE TITLE
License

### ISSUE THREAD

**Issue by a-w50** [TheLartians/Ccache.cmake#8]
Hi,

would it be possible to put this repository under a specific license?  I would like to include the cmake file in my repository, but without a license, that doesn't seem to be allowed.

Thanks

**Comment by TheLartians** [comment]
Hey, thanks for the issue! Definitely, this looks like an oversight on my side.

**Comment by TheLartians** [comment]
Actually I just realised that this project is based on code found in [this article](https://crascit.com/2016/04/09/using-ccache-with-cmake/) and I can't find the usage conditions on that site. 

@craigscott-crascit I hope it's ok for me to be using your code here. Could you please clarify on the licensing terms for code taken on your website?

**Comment by craigscott-crascit** [comment]
The site doesn't state the license that applies, which I should probably address at some point. I'll follow-up with you directly, but my intent is that any code samples on my site should be able to be used freely.

**Comment by TheLartians** [comment]
Great, thanks again!
